// Package worksheetrepo exposes separately cloned worksheet repositories to the
// generator's Go module.
package worksheetrepo

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	GenerateDir = "generate"
	OutputPath  = "cmd/generate/worksheets_local.go"
	DefaultRoot = "/users"
)

// Prepare links repositories below usersRoot into generate/ and writes the
// blank imports needed to register their worksheet packages. It reports
// whether the import file changed.
func Prepare(usersRoot string) (bool, error) {
	root := usersRoot
	if root == "" {
		root = DefaultRoot
		if HasLocalUserDirectories(GenerateDir) {
			root = GenerateDir
		}
	}
	if filepath.Clean(root) != filepath.Clean(GenerateDir) {
		if err := LinkUserRepositories(root, GenerateDir); err != nil {
			return false, err
		}
	}
	packages, err := Packages(root)
	if err != nil {
		return false, err
	}
	data, err := importSource(packages)
	if err != nil {
		return false, err
	}
	old, err := os.ReadFile(OutputPath)
	if err == nil && string(old) == string(data) {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if err := os.WriteFile(OutputPath, data, 0o644); err != nil {
		return false, err
	}
	return true, nil
}

func importSource(packages []string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/importworksheets; DO NOT EDIT.\n")
	b.WriteString("package main\n\nimport (\n")
	for _, pkg := range packages {
		fmt.Fprintf(&b, "\t_ %q\n", "learningmaterial/"+filepath.ToSlash(pkg))
	}
	b.WriteString(")\n")
	return format.Source([]byte(b.String()))
}

// HasLocalUserDirectories reports whether root contains worksheet repository
// directories (including symlinks to directories).
func HasLocalUserDirectories(root string) bool {
	entries, err := os.ReadDir(root)
	if err != nil {
		return false
	}
	for _, entry := range entries {
		if !strings.HasPrefix(entry.Name(), ".") && isDirOrSymlinkToDir(root, entry) {
			return true
		}
	}
	return false
}

// isDirOrSymlinkToDir reports whether the entry is a directory or a symlink
// whose target is a directory (os.ReadDir's IsDir never follows symlinks).
func isDirOrSymlinkToDir(root string, entry os.DirEntry) bool {
	if entry.IsDir() {
		return true
	}
	info, err := os.Stat(filepath.Join(root, entry.Name()))
	return err == nil && info.IsDir()
}

// LinkUserRepositories exposes every repository below usersRoot as a symlink
// below generateDir, keeping the worksheet source physically outside the core
// repository while making it part of the core Go module during a build.
//
// One layout needs no link: the sandbox request clones hold a REAL directory
// at generate/<user> (the standalone worksheet clone). When generate/<user>
// already is that directory (resolving to the usersRoot entry), linking is a
// no-op. A real directory pointing anywhere else is still an error: silently
// replacing it could hide unmerged work.
func LinkUserRepositories(usersRoot, generateDir string) error {
	users, err := os.ReadDir(usersRoot)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if err := os.MkdirAll(generateDir, 0o755); err != nil {
		return err
	}
	for _, user := range users {
		if !user.IsDir() || strings.HasPrefix(user.Name(), ".") {
			continue
		}
		source, err := filepath.Abs(filepath.Join(usersRoot, user.Name()))
		if err != nil {
			return err
		}
		link := filepath.Join(generateDir, user.Name())
		current, err := os.Readlink(link)
		if err == nil {
			if current == source {
				continue
			}
			if err := os.Remove(link); err != nil {
				return fmt.Errorf("replace %s: %w", link, err)
			}
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("%s exists and is not a symlink", link)
		}
		if sameResolvedDir(link, source) {
			// Sandbox layout: generate/<user> is already the repository
			// itself (a standalone clone), no symlink needed.
			continue
		}
		if err := os.Symlink(source, link); err != nil {
			return err
		}
	}
	return nil
}

// sameResolvedDir reports whether path exists and resolves (all symlinks
// evaluated) to the same directory as target.
func sameResolvedDir(path, target string) bool {
	p, err := filepath.EvalSymlinks(path)
	if err != nil {
		return false
	}
	t, err := filepath.EvalSymlinks(target)
	if err != nil {
		return false
	}
	return p == t
}

// Packages returns the worksheet package import paths for repositories below
// root. A worksheet is any immediate child directory containing a non-test Go
// source file.
func Packages(root string) ([]string, error) {
	users, err := os.ReadDir(root)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var packages []string
	for _, user := range users {
		if !user.IsDir() || strings.HasPrefix(user.Name(), ".") {
			continue
		}
		userDir := filepath.Join(root, user.Name())
		sheets, err := os.ReadDir(userDir)
		if err != nil {
			return nil, err
		}
		for _, sheet := range sheets {
			if !sheet.IsDir() || strings.HasPrefix(sheet.Name(), ".") {
				continue
			}
			dir := filepath.Join(userDir, sheet.Name())
			entries, err := os.ReadDir(dir)
			if err != nil {
				return nil, err
			}
			for _, entry := range entries {
				if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") && !strings.HasSuffix(entry.Name(), "_test.go") {
					packages = append(packages, filepath.Join(GenerateDir, user.Name(), sheet.Name()))
					break
				}
			}
		}
	}
	sort.Strings(packages)
	return packages, nil
}
