package main

import (
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const outputPath = "cmd/generate/worksheets_local.go"

func main() {
	packages, err := worksheetPackages("generate")
	if err != nil {
		log.Fatal(err)
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/importworksheets; DO NOT EDIT.\n")
	b.WriteString("package main\n\nimport (\n")
	for _, pkg := range packages {
		fmt.Fprintf(&b, "\t_ %q\n", "learningmaterial/"+filepath.ToSlash(pkg))
	}
	b.WriteString(")\n")
	data, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(outputPath, data, 0o644); err != nil {
		log.Fatal(err)
	}
}

func worksheetPackages(root string) ([]string, error) {
	users, err := os.ReadDir(root)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var packages []string
	for _, user := range users {
		if !user.IsDir() || strings.HasPrefix(user.Name(), ".") {
			continue
		}
		userDir := filepath.Join(root, user.Name())
		sheets, err := os.ReadDir(userDir)
		if err != nil {
			return nil, err
		}
		for _, sheet := range sheets {
			if !sheet.IsDir() || strings.HasPrefix(sheet.Name(), ".") {
				continue
			}
			dir := filepath.Join(userDir, sheet.Name())
			entries, err := os.ReadDir(dir)
			if err != nil {
				return nil, err
			}
			for _, entry := range entries {
				if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") && !strings.HasSuffix(entry.Name(), "_test.go") {
					packages = append(packages, dir)
					break
				}
			}
		}
	}
	sort.Strings(packages)
	return packages, nil
}
